Repository CompFUSE/DCA, pull requests merged in 2018-09, with the labels that each got.

#15 Changed measurements parameter.
  include/dca/parallel/util/get_workload.hpp
  include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_accumulator.hpp
  include/dca/phys/dca_step/cluster_solver/ctaux/ctaux_cluster_solver.hpp
  include/dca/phys/dca_step/cluster_solver/ss_ct_hyb/ss_ct_hyb_cluster_solver.hpp
  include/dca/phys/dca_step/cluster_solver/stdthread_qmci/stdthread_qmci_accumulator.hpp
  include/dca/phys/dca_step/cluster_solver/stdthread_qmci/stdthread_qmci_cluster_solver.hpp
  include/dca/phys/dca_step/cluster_solver/thread_task_handler.hpp
  include/dca/phys/parameters/mci_parameters.hpp
  test/integration/ctaux/bilayer_lattice/Nc1_interband/input.bilayer_lattice_Nc1_interband.json
  test/integration/ctaux/bilayer_lattice/Nc1_intra_plus_interband/input.bilayer_lattice_Nc1_intra_plus_interband.json
  test/integration/ctaux/bilayer_lattice/Nc1_intraband/input.bilayer_lattice_Nc1_intraband.json
  test/integration/ctaux/square_lattice/Nc4_nn/input.square_lattice_Nc4_nn.json
  test/integration/ctaux/square_lattice/Nc4_onSite_plus_nn/input.square_lattice_Nc4_onSite_plus_nn.json
  test/integration/statistical_tests/real_materials/NiO_fullDCA.cpp
  test/integration/statistical_tests/real_materials/NiO_stattest.cpp
  test/integration/statistical_tests/real_materials/input_NiO.json
  test/integration/statistical_tests/square_lattice/ctaux_square_lattice_verification_stattest.cpp
  test/integration/statistical_tests/square_lattice/square_lattice_input.json
  test/integration/stdthread_qmci/stdthread_ctaux_tp_test_input.json
  test/system-level/analysis/dca_pp_up_down_full/input_tp.json
  test/system-level/analysis/dca_pp_up_down_sym/input_tp.json
  test/system-level/analysis/dcaplus_pp_up_down_full/input_tp.json
  test/system-level/analysis/dcaplus_pp_up_down_sym/input_tp.json
  test/system-level/dca/input.dca_sp_DCA+_mpi_test.json
  test/system-level/dca/input.dca_sp_DCA+_thread_test.json
  test/unit/phys/dca_step/cluster_solver/input.json
  test/unit/phys/parameters/mci_parameters/input_read_all.json
  test/unit/phys/parameters/mci_parameters/mci_parameters_test.cpp
  tools/complete_input.json
  tools/cooldown/input_sp.json.in
  tools/cooldown/input_tp.json.in
  tools/parameters_old_to_new.json
  tutorials/tc/input_sp.json.in
  tutorials/tc/input_tp.json.in
  tutorials/tc/preconfigured/T=0.07/input_sp.json
  tutorials/tc/preconfigured/T=0.07/input_tp.json
  tutorials/tc/preconfigured/T=0.08/input_sp.json
  tutorials/tc/preconfigured/T=0.08/input_tp.json
  tutorials/tc/preconfigured/T=0.09/input_sp.json
  tutorials/tc/preconfigured/T=0.09/input_tp.json
  tutorials/tc/preconfigured/T=0.1/input_sp.json
  tutorials/tc/preconfigured/T=0.1/input_tp.json
  tutorials/tc/preconfigured/T=0.125/input_sp.json
  tutorials/tc/preconfigured/T=0.25/input_sp.json
  tutorials/tc/preconfigured/T=0.5/input_sp.json
  tutorials/tc/preconfigured/T=0.75/input_sp.json
  tutorials/tc/preconfigured/T=1/input_sp.json
Labels: API change

#17 Support finding MPI using find_package(MPI) for local compilation
  cmake/dca_mpi.cmake
  cmake/dca_testing.cmake
  src/parallel/mpi_concurrency/CMakeLists.txt
Labels: enhancement

#37 empty vectors don't allocate.
  include/dca/linalg/vector.hpp
Labels: good first issue

#38 Vertex frequency domain
  include/dca/phys/domains/time_and_frequency/vertex_frequency_domain.hpp
Labels: good first issue
